### ISSUE TITLE
Parameterized channel

### ISSUE THREAD

**Issue by zerkms** [symfony/monolog-bundle#122]
At the moment the channel parameter is taken as-is:

                $loggerId = sprintf('monolog.logger.%s', $tag['channel']);
                $this->createLogger($tag['channel'], $loggerId, $container);

whereas I find it useful if it was possible to make it a parameter so that you only needed to specify/change it in one place.

Thoughts?

**Comment by Seldaek** [comment]
Sorry but not sure what you mean.. Do you mean you'd like if it resolved the `$tag['channel']` for parameters before using it? If so that sounds alright to me and please send a pull request :)

**Comment by zerkms** [comment]
Good :-)

And, yes, that's what I meant

**Comment by Taluu** [comment]
@zerkms you should maybe close this ticket as the resulting PR was merged ;)
