### ISSUE TITLE
Error: "You have requested a synthetic service ("request")." when using excluded_404s

### ISSUE THREAD

**Issue by yannickl88** [symfony/monolog-bundle#123]
Whey I configure the bundle to use `excluded_404s` for a `fingers_crossed` handler I get the following error:
```
RuntimeException in ContainerBuilder.php line 915:
You have requested a synthetic service ("request"). The DIC does not know how to construct this service.
```
When looking in the code, I think this causes the error (MonologExtension.php line 293-298)
```php
} elseif (!empty($handler['excluded_404s'])) {
    $activationDef = new Definition('%monolog.activation_strategy.not_found.class%', array($handler['excluded_404s'], $handler['action_level']));
    $activationDef->addMethodCall('setRequest', array(new Reference('request', ContainerInterface::NULL_ON_INVALID_REFERENCE, false)));
    $container->setDefinition($handlerId.'.not_found_strategy', $activationDef);
    $activation = new Reference($handlerId.'.not_found_strategy');
} else {
```

I'm using symfony 2.6.7 with monolog-bundle 2.7.1

My guess is that the MonologExtension should use the request stack, but that might not be compatible with older versions of symfony.

**Comment by Seldaek** [comment]
Yeah and in my experience this isn't an issue so I am not sure why you experience that.
