### ISSUE TITLE
Possible 2.9 release?

### ISSUE THREAD

**Issue by weaverryan** [symfony/monolog-bundle#154]
Hi guys!

Sorry to bother - but there are a set of commits just sitting in master (https://github.com/symfony/monolog-bundle/compare/v2.8.2...master) and I'd like to get those into a proper release (probably 2.9 to follow semver). Could one of you tag a release? Or if you want another maintainer to help with releases, let me know.

Thanks!

**Comment by weaverryan** [comment]
Friendly ping! We've got a few features dating back about 3 months that aren't on a stable release yet.

**Comment by xabbuh** [comment]
Please note that #155 should be merged before the tag so that it's possible to use #153 with XML configurations.

**Comment by weaverryan** [comment]
And now #155 *is* merged. I don't know of any other blockers for a tag.

**Comment by weaverryan** [comment]
Friendly (I know, probably annoying) ping!

Also, if I can help out this bundle as another maintainer, I'm open to that :)

**Comment by Seldaek** [comment]
https://github.com/symfony/monolog-bundle/releases/tag/v2.9.0 :tada:
