### ISSUE TITLE
support "release" parameter for RavenHandler?

### ISSUE THREAD

**Issue by kcivey** [symfony/monolog-bundle#161]
It looks like RavenHandler expects to find "release" under "extra" or "context", but the bundle doesn't allow setting either of those values in config.yml. Am I missing something?

**Comment by stof** [comment]
the context is passed when calling the logger (it is the last argument of all logging methods in PSR-3). And extra is meant to be filled by Monolog processors.
So there is nothing to configure in config.yml for them (well, you can configure processors).

**Comment by kcivey** [comment]
Thanks, but if the logger is being called automatically by the bundle, is there a way to include the release? I have this under `handlers` under `monolog`:

        sentry:
            type: raven
            dsn: '%sentry.dsn%'
            client_id: ~ # does this do anything?
            level: warning
            bubble: false

I tried adding another property `extra: {release: '%version%'}` (or with `context` instead of `extra`), but I see now that that's not going to be the way. Are you saying it requires a special processor?

**Comment by stof** [comment]
well, you can register a processor adding this in extras for all log records (processors are registered by a tag on a service)

**Comment by Seldaek** [comment]
Actually sorry I just realize we added a setRelease to last release of monolog, so I'll add support for this here in a moment.
