### ISSUE TITLE
Implicity calling the setLogger method

### ISSUE THREAD

**Issue by xocasdashdash** [symfony/monolog-bundle#164]
Hi,

I've been using this bundle for a while and I've been wondering about something. When you tag a service with the monolog.logger tag you have to add to the service definition the method call to setLogger with the logger service so it can replace it with the correct channel one. 
Would you be open to a PR to add support to using reflection to add the call to setLogger if the class has the method setLogger (or implements the LoggerInterface) ?

**Comment by Seldaek** [comment]
Isn't it what https://github.com/symfony/monolog-bundle/pull/143 does with autowiring?

**Comment by xocasdashdash** [comment]
mmm I don't think so (first time autowire_r_). I just set up the following test (Symfony 2.8): [link to repo with test](https://github.com/xocasdashdash/monolog-test)

I've setted up the service1 service to be autowired and I use the logger trait in the service to avoid problems with annotations, but when i run the dev server and hit localhost:8000 i get a "Call to a member function error()"

Is anything wrong on my config? If something were wrong with my config, this wouldn't be supported in anything that's not Symfony 2.8+

**Comment by xocasdashdash** [comment]
@dunglas you did the PR with the autowiring fix, is there anything wrong with my code for the autowiring to not kick in? Is it necessary to add the calls to setLogger?

**Comment by dunglas** [comment]
You need to use MonologBundle 2.11.0 or superior.

**Comment by dunglas** [comment]
@xocasdashdash Setter autowiring is not supported yet. It will be when symfony/symfony#20167 will be merged. For now you need to type hint the Logger interface in the constructor of your class.

**Comment by Tobion** [comment]
Autowiring based on reflection has been removed in symfony 3.4/4. Either use constructor autowiring or explicit setter autowiring: https://symfony.com/doc/current/service_container/autowiring.html#autowiring-other-methods-e-g-setters
