### ISSUE TITLE
`excluded_404s` does not work for symfony 3

### ISSUE THREAD

**Issue by zerkms** [symfony/monolog-bundle#166]
The generated `NotFoundActivationStrategy` service in a service locator looks like:

```php
    protected function getMonolog_Handler_Errors_NotFoundStrategyService()
    {
        $this->services['monolog.handler.errors.not_found_strategy'] = $instance = new \Symfony\Bundle\MonologBundle\NotFoundActivationStrategy(array(0 => '^/'), 400);

        $instance->setRequest(NULL);

        return $instance;
    }
```

So the request is never passed into the object and it does not take the passed url regexes into account.

**Comment by zerkms** [comment]
So, seems like there is a new implementation there already https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Monolog/Handler/FingersCrossed/NotFoundActivationStrategy.php but not sure if it's possible to switch to it so that it also worked for v2.3

**Comment by Seldaek** [comment]
This is related to https://github.com/symfony/monolog-bundle/pull/94

**Comment by BPScott** [comment]
Found that this was biting me today, so I've done a bit of digging (this is likely to be obvious to the maintainers but hey why not):

excluded_404s no longer works in Symfony 3.0 as currently monolog-bundle [injects a reference to request from the service container](https://github.com/symfony/monolog-bundle/blob/e7caf4936c7be82bc6d68df87f1d23a0d5bf6e00/DependencyInjection/MonologExtension.php#L323-L326) into the NotFoundActivationStrategy. Having Request in the service container was [deprecated in Symfony 2.7 in favor of using RequestStack, and subsequently removed in Symfony 3.0](http://symfony.com/blog/new-in-symfony-2-7-dependency-injection-improvements#deprecated-synchronized-services). As the NotFoundActivationStrategy  never gets a request object it can never check the path of that request and thus the log line never excluded.

The concept of RequestStack was added in [Symfony 2.4](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack). 
The implementation of [NotFoundActivationStrategy in monolog-bridge](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Monolog/Handler/FingersCrossed/NotFoundActivationStrategy.php) uses RequestStack and was added as part of Symfony 2.6.


#94 talks about maintaining compatibility with 2.3, but given that [2.3 entered the security fixes only part of it's LTS lifecycle this month (May 2016)](http://symfony.com/roadmap?version=2.3#checker) I don't think the extra effort to support it is worthwhile.

From what I can tell, #94 needs to be updated to pass the RequestStack into the NotFoundActivationStrategy's constructor [here](https://github.com/symfony/monolog-bundle/blob/e7caf4936c7be82bc6d68df87f1d23a0d5bf6e00/DependencyInjection/MonologExtension.php#L323-L326) then it can be merged and a release can be tagged that supports Symfony 2.6+. @Seldaek / @fabpot I can give that a go at some point soonish if you're busy with other stuff.

**Comment by BPScott** [comment]
Oh, and moving away from using `request` shall also render #123 invalid as we won't be using a synthetic service.

**Comment by rommsen** [comment]
Is there any plan to include a solution for this in an upcoming release? We are using the fingers crossed handler to get notified via hipchat when one of our system throws an Exception. Since moving to Symfony 3 we are bombarded with 404 notifications from bots trying to access wp_admin.php admin.php etc. which renders the notifications almost useless. 

Is there any other way to mitigate this?

**Comment by zerkms** [comment]
@rommsen 

you can create a custom activation strategy. This is how I implemented it for my projects

```php

use Monolog\Handler\FingersCrossed\ActivationStrategyInterface;
use Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class NotFound implements ActivationStrategyInterface
{
    private $errorLevelActivationStrategy;

    public function __construct($actionLevel)
    {
        $this->errorLevelActivationStrategy = new ErrorLevelActivationStrategy($actionLevel);
    }

    public function isHandlerActivated(array $record)
    {
        if (isset($record['context']['exception'])) {
            if ($record['context']['exception'] instanceof NotFoundHttpException) {
                return false;
            }
        }

        return $this->errorLevelActivationStrategy->isHandlerActivated($record);
    }
}
```

**Comment by rommsen** [comment]
@zerkms Thanks a million. This led me in the right direction.

If anybody stumbles over this, here is how I solved it for us:
The implementation of [NotFoundActivationStrategy](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Monolog/Handler/FingersCrossed/NotFoundActivationStrategy.php) in monolog-bridge uses RequestStack and was added as part of Symfony 2.6.

So I added a service definition for this class.
```yaml
custom_monolog_fingers_crossed_handler_activation_strategy:
  class: Symfony\Bridge\Monolog\Handler\FingersCrossed\NotFoundActivationStrategy
  arguments:
    - "@request_stack"
    - ["^/"]
    - "ERROR"
```
First parameter is the RequestStack, second parameter are the "excluded_404s" or blacklist, third parameter is the action_level, when the fingers_crossed handler is activated (we use ERROR in this case but it defaults to WARNING in monolog-bundle).

Then I added this service as the activation_strategy parameter in my monolog config:

```yaml
monolog:
  ...
  handlers:
     ...
          type: fingers_crossed
          ...
          activation_strategy: custom_monolog_fingers_crossed_handler_activation_strategy
```
**Important**: I had to remove the "excluded_404s" parameter, because it is not allowed in combination with a custom activation_strategy.

Hope this helps someone.

**Comment by Laurent3170** [comment]
@rommsen I am facing the same problem (as everyone using this functionality should). Do you think that I should implement your solution or wait that an official correction comes ?

**Comment by rommsen** [comment]
@Laurent3170 I think this depends on how much pain you are feeling right now :smile: . For us it was just way too much noise so I implemented it and never looked back. In case of something more "official" arrives, it would not be to much work to revert.

**Comment by Laurent3170** [comment]
@rommsen just a small question how do you separate multiple excluded in the second argument ? i.e
```
- ^/admin.php
- ^/administrator
- ^/configuration.php
- ^/index.php
```

**Comment by zerkms** [comment]
@Laurent3170 

I believe

```yaml
- ["^/admin.php", "^/administrator", ...]
```

would work

**Comment by Laurent3170** [comment]
Ok, I was guessing between "," and "|" but I can't make it work (for the time being) with just only one...
Thanks for your answer

**Comment by Laurent3170** [comment]
Yes that's "," I had to clear the cache... Thanks

**Comment by Laurent3170** [comment]
As I'm quite new to Symfony, can you explain what it means ? Can we revert to what is explained in the Symfony docs ?

**Comment by StevendeVries** [comment]
@Laurent3170 with the mentioned fix by fabpot the 404s (NotFoundActivationStrategy) should work as documented for symfony 3.0.

**Comment by Laurent3170** [comment]
Argh, thanks for your answer but it seems not...
I am using `monolog/monolog 1.21.0` and `symfony/monolog-bundle 2.12.0` along with `symfony 3.1.6`

**Comment by StevendeVries** [comment]
@Laurent3170 try monolog-bundle 3.0: https://github.com/symfony/monolog-bundle/releases/tag/3.0.0

**Comment by Laurent3170** [comment]
@StevendeVries Thanks again for your prompt answer. I haven't seen that a 3.0 version was available as I was looking in the "branches" part and not in the "tags" one. So... It works! :smile:

**Comment by Laurent3170** [comment]
Don't know where to "ask" and it seems, here it may be a place of concerns. As those servers which bother us by asking pages using specific urls, i.e. `/admin`, I was wondering of not setting them in config_prod.yml to avoid receiving monolog notifications but to build a specific Controller to redirect them to somewhere...
I know I can do it by myself, but maybe there are things I haven't thought about and maybe you know a good place to send them to...

**Comment by rommsen** [comment]
> maybe you know a good place to send them to...

to hell maybe? :smile: (scnr)

**Comment by thelem** [comment]
I'm not really familiar with the Symfony documentation standards, but this seems like it should be mentioned on https://symfony.com/doc/current/logging/monolog_regex_based_excludes.html (at least for Symfony 3.0 and 3.1, perhaps for later versions too). Or maybe bump Symfony's dependency to ensure people don't see the problem on later versions?

**Comment by xabbuh** [comment]
@thelem Would you mind opening an issue in the docs repository?
