### ISSUE TITLE
Send mail problem with deduplicated after upgrade

### ISSUE THREAD

**Issue by tsifra** [symfony/monolog-bundle#182]
Recently there were two updates: swift_mailer and monolog. Somehow monolog settings for sending email breaks sending email for everything. If i switch off deduplicated mode everything works just fine.

It seems, that monolog overwrites swiftmailer setting set in config.xml Here are logs for test messages from mailserver.
without deduplicated:
Nov  6 10:44:38 [SERVERNAME] postfix/smtpd[11968]: connect from [DOMAINNAME][IPADDRESS]
Nov  6 10:44:38 [SERVERNAME] postfix/smtpd[11968]: Anonymous TLS connection establi
shed from [DOMAINNAME][[IPADDRESS]]: TLSv1 with cipher ECDHE-RSA-AES128-SH
A (128/128 bits)
Nov  6 10:44:38 [SERVERNAME] postfix/smtpd[11968]: 813E35D7D7: client=[DOMAINNAME][[IPADDRESS]],
sasl_method=LOGIN, sasl_username=
Nov  6 10:44:38 [SERVERNAME] postfix/cleanup[11970]: 813E35D7D7: message-id=<>
Nov  6 10:44:38 [SERVERNAME] postfix/qmgr[24479]: 813E35D7D7: from=<>, size=16405, nrcpt=1 (queue active)
Nov  6 10:44:38 [SERVERNAME] postfix/smtpd[11968]: disconnect from [DOMAINNAME]
[[IPADDRESS]] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Nov  6 10:44:42 [SERVERNAME] postfix/smtp[11971]: 813E35D7D7: to=<>,
relay=mxs.mail.ru[94.100.180.150]:25, delay=4.1, delays=0.23/0.01/1.5
/2.3, dsn=2.0.0, status=sent (250 OK id=1c3I89-0006wM-4r)
Nov  6 10:44:42 [SERVERNAME] postfix/qmgr[24479]: 813E35D7D7: removed

with deduplicated:
Nov  6 10:48:04 [SERVERNAME] postfix/smtpd[12377]: NOQUEUE: reject: RCPT from ():
504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=<> to=<> proto=ESMTP helo=<localhost>

**Comment by lyrixx** [comment]
Hello @tsifra 
Did you manage to fix this issue?

**Comment by tsifra** [comment]
> Hello @tsifra
> Did you manage to fix this issue?

Hi, @lyrixx can't even remember how solved this. Possibly newer versions of symfony are working fine.
