### ISSUE TITLE
monolog.activation_strategy.not_found gets created without parameters inside container

### ISSUE THREAD

**Issue by Loupax** [symfony/monolog-bundle#192]
I have just upgraded my symfony/symfony installation to 3.2 and symfony/monolog-bundle to 3.0.1 and my smoke tests fail when they try to access the following services:

[monolog.activation_strategy.not_found](https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml#L21) and [monolog.handler.fingers_crossed.error_level_activation_strategy](https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml#L22)

The error I'm getting is the following:

```
Catchable Fatal Error: 
Argument 1 passed to Symfony\Bridge\Monolog\Handler\FingersCrossed\NotFoundActivationStrategy::__construct() 
must be an instance of Symfony\Component\HttpFoundation\RequestStack, none given, called
 in /project/var/cache/dev/appDevDebugProjectContainer.php on line 2769 and defined
```
and when I go and see my `appTestDebugProjectContainer.php` file I see these services have no arguments in their construction

```
    /**
     * Gets the 'monolog.activation_strategy.not_found' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Symfony\Bridge\Monolog\Handler\FingersCrossed\NotFoundActivationStrategy A Symfony\Bridge\Monolog\Handler\FingersCrossed\NotFoundActivationStrategy instance
     */
    protected function getMonolog_ActivationStrategy_NotFoundService()
    {
        return $this->services['monolog.activation_strategy.not_found'] = new \Symfony\Bridge\Monolog\Handler\FingersCrossed\NotFoundActivationStrategy();
    }
```

```
    /**
     * Gets the 'monolog.handler.fingers_crossed.error_level_activation_strategy' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy A Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy instance
     */
    protected function getMonolog_Handler_FingersCrossed_ErrorLevelActivationStrategyService()
    {
        return $this->services['monolog.handler.fingers_crossed.error_level_activation_strategy'] = new \Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy();
    }
```

**Comment by Sander-Toonen** [comment]
Same here. As far as I can tell these services are never used. The MonologExtension creates new definitions (with the needed arguments) for every handler that needs them. Would it be possible to remove the definitions from ``monolog.xml``?

**Comment by asquel** [comment]
Same here,
It's because of a container smoke test : 

`public function testContainerServices()
    {
        $client = static::createClient();

        foreach ($client->getContainer()->getServiceIds() as $serviceId) {
            try {
                $service = $client->getContainer()->get($serviceId);
                $this->assertNotNull($service);
            } catch (InactiveScopeException $e) {}
        }
    }`

**Comment by Soullivaneuh** [comment]
Same issue with smoke test as @asquel said.

Got similar error for `Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy`:

```
2) Tests\ServiceAvailabilityTest::testServiceInstance with data set #404 ('monolog.handler.fingers_cross...rategy')
Missing argument 1 for Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy::__construct(), called in /code/app/cache/test/appTestDebugProjectContainer.php on line 8819 and defined

/code/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:73
/code/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossed/ErrorLevelActivationStrategy.php:25
/code/app/cache/test/appTestDebugProjectContainer.php:8819
/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:314
/code/tests/ServiceAvailabilityTest.php:36
```
