### ISSUE TITLE
After updating "logger" alias isn't resolved anymore

### ISSUE THREAD

**Issue by korsmakolnikov** [symfony/monolog-bundle#194]
We have a Symfony 2.8 stack with standard requirement:
`        "symfony/monolog-bundle": "~2.4",
`

__Yesterday we have update requirements, so now monolog is locked to version 2.12.0. 
Somehow all service where inject _@logger_ fail in a 500 error because of type hinting (Nulllogger is injected).__ I check monolog.xml inside vendor/symfon/monolog-bundle/resources/config and alias is still there. 

Then I try if one of the broken service works injecting _@monolog.logger_ instead of _@logger_ and it does.
I solved this with a new alias in our service.yml. 

Anyway I'm asking why this happen.

**Comment by xabbuh** [comment]
@korsmakolnikov What is the type hint you are using?

**Comment by stof** [comment]
MonologBundle does not define any NullLogger service. So this would come from another bundle.

Any anyway, typehinting the PSR-3 LoggerInterface should work with a NullLogger too.

I'm closing this old issue anyway.
