### ISSUE TITLE
Usages of deprecated DefinitionDecorator

### ISSUE THREAD

**Issue by chalasr** [symfony/monolog-bundle#201]
The current master makes use of `DefinitionDecorator` which will lead to deprecation notices as of symfony 3.3 and fatal errors as of 4.0.
Should we replace any `DefinitionDecorator` occurrence by `ChildDefinition` and update the `symfony/dependency-injection` requirement to `~3.3`  on master right now? 
If so I can work on this.

**Comment by stof** [comment]
No we should not bump the requirement (otherwise we would have to maintain 2 versions in parallel due to the LTS, which is not worth it IMO). We should select the right class based on availability.
