### ISSUE TITLE
Autowiring the PSR-3 interface does not correctly map the channels

### ISSUE THREAD

**Issue by tehplague** [symfony/monolog-bundle#218]
Configuring the logging channel via a tag does only work if you do not autowire Monolog via a PSR-3 constructor argument. If your service expects a `Psr\Log\LoggerInterface` and you are using autowiring, the `LoggerChannelPass` does not find your definitions. That is IMHO because Symfony autowires the `monolog.logger` service and the compiler pass expects a service argument referring to the `logger` service.

I think the pass should be modified from
```
if ($argument instanceof Reference && 'logger' === (string) $argument) {
```
to
```
if ($argument instanceof Reference && in_array((string) $argument, ['logger', 'monolog.logger'], true)) {
```
(two occurrences)

Then, definitions like the following
```
        <service id="Foo\FooService">
            <argument>logger</argument>
            <argument>%some_param%</argument>
            <tag name="monolog.logger" channel="foo" />
        </service>
```

can simply be written as
```
        <service id="Foo\FooService">
            <argument key="$param">%some_param%</argument>
            <tag name="monolog.logger" channel="foo" />
        </service>
```
even if the expect a PSR-3 `LoggerInterface`.

**Comment by stof** [comment]
Actually, it does not autowire `monolog.logger`. It autowires `Psr\Log\LoggerInterface` (which is then an alias pointing to `logger`)

**Comment by tehplague** [comment]
And since `logger` is only an alias for `monolog.logger` the autowired definition finishes at `monolog.logger` which does not match.

**Comment by stof** [comment]
@tehplague autowiring does not resolve aliases when setting a reference. and references don't resolve aliases either

**Comment by tehplague** [comment]
I'm with you, @stof, but the point is, that autowiring _and_ configuring the logger channel via tag at the same time are currently not going well together. Since Symfony is pushing hard towards autowiring with its 3.3 release it should at least be documented that MonologBundle has a shortcoming in here. Or the compiler pass should be extended to consider the service argument provided by the DI container, i.e. `monolog.logger` instead of `logger`.

For the same reason, it is currently not possible to set the logging channel resource-wide by adding the channel tag to `_defaults` while using the short service syntax and omitting the service arguments altogether.

**Comment by stof** [comment]
@tehplague what I'm saying is that allowing `monolog.logger`in the condition will **not** fix the compiler pass. What must be added is `Psr\Log\LoggerInterface` (which is what will be referenced by autowiring)

**Comment by dbu** [comment]
this should at least generate a warning or error when building the container. silently not working makes it hard to debug.

i created https://github.com/symfony/symfony-docs/pull/9047 so that its at least documented.

**Comment by ianfp** [comment]
For those who need a workaround, you can [manually wire the logger](https://symfony.com/doc/3.4/service_container.html#manually-wiring-arguments) while still autowiring everything else:

```yaml
services:
  _defaults:
    autowire: true
  Class\Name\Of\YourService:
    arguments:
      $logger: '@logger'
```

**Comment by xabbuh** [comment]
see #251
