### ISSUE TITLE
Missing configuration option for StreamHandler

### ISSUE THREAD

**Issue by pbeschel** [symfony/monolog-bundle#259]
It will be nice to have an option to configure "lock" on StreamHandler
There is existing PR for it [here](https://github.com/symfony/monolog-bundle/pull/242)

**Comment by emporium-nsalter** [comment]
I definitely want this

**Comment by pbeschel** [comment]
I rly need this in my project. Can you please take a look?

**Comment by lyrixx** [comment]
Fixed thanks to #242
