### ISSUE TITLE
Overriding Handlers isn't possible anymore

### ISSUE THREAD

**Issue by zaiddabaeen** [symfony/monolog-bundle#263]
With the introduction of v3, overriding handlers is not possible anymore through just the handler configuration.

I am using Symfony 4.

Previously, the slack handler could have been overridden by setting the `monolog.handler.slack.class` parameter as in:
https://github.com/symfony/monolog-bundle/blob/2.x/Resources/config/monolog.xml

Now, it looks like this: https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml
With no parameter to override handlers.

To achieve the same result, one would have to create a new service, and pass to it all the handler parameters, then call the original constructor of the handler.

Can we have the handler overriding parameters back?

**Comment by Seldaek** [comment]
All these parameters lead to overhead - see https://github.com/symfony/symfony/issues/11881 - so no they are not coming back sorry.
