### ISSUE TITLE
Cannot remove it with composer

### ISSUE THREAD

**Issue by albawan** [symfony/monolog-bundle#288]
Somehow, on production, I cannot remove this package with composer. I tried just about everything, also see [https://stackoverflow.com/questions/53389744/composer-cannot-remove-dependency-on-production](url). 

The error I keep on getting is:

> symfony/monolog-bundle (>=3.1): From github.com/symfony/recipes:master Executing script cache:clear [KO] [KO] Script cache:clear returned with error code 255 !! !!
> [WARNING] Some commands could not be registered:
> !! !! In srcProdProjectContainer.php line 939: !!
> !! Class 'Symfony\Bridge\Monolog\Logger' not found !!
> !! !! !! [WARNING] Some commands could not be registered:
> !! !! In srcProdProjectContainer.php line 939: !!
> !! Class 'Symfony\Bridge\Monolog\Logger' not found !!
> !! !! !! In srcProdProjectContainer.php line 923: !!
> !! Attempted to load class "Logger" from namespace "Symfony\Bridge\Monolog". !! Did you forget a "use" statement for e.g. "Symfony\Component\HttpKernel\Log !! \Logger" or "Symfony\Component\HttpKernel\Tests\Logger"? !!
> !! !! cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] !!
> !!
> 
> Removal failed, reverting ./composer.json to its original content.

**Comment by stof** [comment]
the issue on production is actually not related to MonologBundle, but to `cache:clear`. Running `cache:clear` requires booting the kernel first to start the CLI. In non-debug mode, booting the kernel will use the existing container cache if it exists (without checking its freshness, as that's precisely the main goal of the debug mode). And a cache created before the removal of a bundle might not be usable anymore when the dependency is gone.
