### ISSUE TITLE
Elasticsearch configuration for host

### ISSUE THREAD

**Issue by barell** [symfony/monolog-bundle#296]
Hi all,

At the moment it is not really clear how to configure Elasticearch. I had to spent some time debugging only to find out that when you specify "host" parameter, it can't include http:// part in it. 

I think it would be great to update documentation to mention it, or even better, update code to either accept protocol part of the host URL or throw error so developers know what is going on.

I can create a PR for this but wanted to know your thoughts.

**Comment by lyrixx** [comment]
Since we are using elastica, the simplest thing here is to update the documentation.
Would you mind submit a PR?
Thanks

**Comment by filkaris** [comment]
I took the liberty of opening one with a small update in the documentation
