### ISSUE TITLE
Removed Hanlders of monolog 2.0 should be reflected on configuration?

### ISSUE THREAD

**Issue by gmponos** [symfony/monolog-bundle#320]
Hello,

There are some handlers that they have been removed from version 2.0

Should this be reflected to the configuration file of the bundle as a deprecations?

I would love to submit a PR fixing this but I search for other examples and I could not find any.

**Comment by gmponos** [comment]
OK I just saw this: https://github.com/symfony/monolog-bundle/pull/321/files

**Comment by Tobion** [comment]
Closing as the PR got merged.
