### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tristanbes** [symfony/monolog-bundle#323]
Hey,

I would like to know if it's possible to tag a new release;

There's interesting features already on master i'd like to use (insightops support, autowiring channels) instead of requiring `dev-master` :)

https://github.com/symfony/monolog-bundle/compare/v3.4.0...master

**Comment by lyrixx** [comment]
Okay. I will look at it

**Comment by dvdknaap** [comment]
when will this package get a update because some composer dependencies are out of date because of this bundle @lyrixx @Seldaek

**Comment by gharlan** [comment]
This can be closed
