### ISSUE TITLE
3.5: Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.   

### ISSUE THREAD

**Issue by andrerom** [symfony/monolog-bundle#330]
Seems some composer.json requirements are wrong somewhere,  as of 3.5 release we get this error:
> Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.   

User can of course force `monolog/monolog: ^1.22` in composer.json, but maybe rather then pushing that on everyone: Monolog  2 could have conflict with Symfony < 5 for instance, or there should be separate version of this bundle for Symfony 5?

That said, AFAIK composer does not have a way to deprecate 3.5.0 release to guarantee people don't get this issue again though...

ℹ️ **How to fix in your project while waiting for fix here:** ℹ️ 
```bash
composer require "monolog/monolog:^1.22"
```

**Comment by GasparMDQ** [comment]
Same issue here. I do have a line on my composer.json saying`"symfony/symfony": "3.4.*"` but still monolog bundle went up to 2.0 which requires S5

**Comment by Mopster** [comment]
I solved it by locking the bundle to 3.4, iy'll will prevent it from updating to 3.5

`"symfony/monolog-bundle": "3.4.0",`

**Comment by GasparMDQ** [comment]
Although both patches work, this is version 3.5 and not 4.0, so compatibility with Symfony < 5 shouldn't be broken as the previous minor version (3.4) supported them.

**Comment by stof** [comment]
Note that this is an issue only for projects using `symfony/symfony`, as this package does not have a requirement on Monolog (as that's an optional dependency).
Projects using component packages (which is the recommended way in Symfony 4+ and the only way compatible with Flex) are fine, because `symfony/monolog-bridge` has the requirement on Monolog and so composer can get the right version.

**Comment by andrerom** [comment]
In our case this is indeed only issue on our Symfony 3.4LTS based versions.

**Comment by pascalaymon** [comment]
I have exactly the same issue on Symfony 3.4.
For now I solve it by the way of @Mopster.

**Comment by stof** [comment]
well, it is not about 3.4 vs 4.x but about `symfony/symfony` vs `symfony/*` packages. It is possible to use the fullstack repo for Symfony 4 (although not recommended, and only if you don't use Flex), and it is possible to use individual packages with 3.4 (btw, you can use Flex with SF 3.4 LTS).

But this is indeed an issue (especially given that `symfony/symfony` was the default setup in 3.x)

**Comment by kl3sk** [comment]
> 
> 
> I have exactly the same issue on Symfony 3.4.
> For now I solve it by the way of @Mopster.

I fix it as well

**Comment by karpilin** [comment]
For those who still want to benefit from monolog-bundle v3.5, just add monolog/monolog dependency to your project.
`composer require "monolog/monolog:~1.25"`

**Comment by smatyas** [comment]
Would merging of this PR prevent this issue? https://github.com/symfony/symfony/pull/32469

**Comment by stof** [comment]
https://github.com/symfony/symfony/pull/32469 will indeed help at least for new SF release, but there will indeed be ways for composer to select Monolog 2 and an older SF version depending on your requirements (but then, you could bump the min patch version of SF in your composer.json too, and we could do it in MonologBundle as well)

**Comment by jdcrecur** [comment]
This issues prevent a composer install on ezplatform 2.5.6

Downgrading monolog to 3.1.2 seems to work

**Comment by derrabus** [comment]
While Symfony 3.4 and Monolog 2 are both supported by the latest version of the bundle, the combination of those two does not work. This is pretty much what the error message says.

> I solved it by locking the bundle to 3.4, it'll will prevent it from updating to 3.5

No, please don't do that. You won't receive any further updates to the bundle which is bad. Pin Monolog to version 1 instead as the error message suggests and you're going to be fine.

**Comment by alongosz** [comment]
> This issues prevent a composer install on ezplatform 2.5.6
> 
> Downgrading monolog to 3.1.2 seems to work

@jdcrecur eZ Platform 2.5.7 will come with downgraded `monolog/monolog` package (via ezsystems/ezplatform@775459dcd4536f2224a3df57029d9ccdaa672440). You can already add this change to your composer.json.

**Comment by botjaeger** [comment]
> > I have exactly the same issue on Symfony 3.4.
> > For now I solve it by the way of @Mopster.
> 
> I fix it as well

mine too

**Comment by pascalaymon** [comment]
> > > I have exactly the same issue on Symfony 3.4.
> > > For now I solve it by the way of @Mopster.
> > 
> > 
> > I fix it as well
> 
> mine too


The first post has been edited. 
A new solution is provided (while waiting fix), I use it in project and it's ok.

**Comment by arashdeepsinghazad** [comment]
I tried
`composer require "monolog/monolog:^1.22`
But when I do
`composer update`. Monolog again gets updated to version 2

**Comment by arashdeepsinghazad** [comment]
Downgradeing `symfony/monolog-bundle`  also didn't work.

**Comment by Tobion** [comment]
Closing as https://github.com/symfony/symfony/pull/32469 is merged.
