### ISSUE TITLE
Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.

### ISSUE THREAD

**Issue by arashdeepsinghazad** [symfony/monolog-bundle#332]
I am using Symfony 3.4.
And it gives "Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1."
I tried many methods to make monolog/monolog[2.0.1] -> monolog/monolog[1.25.0]
My symfony/monolog-bundle is 3.1.0 and the same version is working on my other symfony 3.4 projects.

**Comment by xabbuh** [comment]
duplicate of #330
