### ISSUE TITLE
Why is monolog-bundle configuring prod environment initially with log level "debug"?

### ISSUE THREAD

**Issue by RicoFactset** [symfony/monolog-bundle#339]
Hello,

the GuardAuthenticationListener for instance logs on "info" log level:
$this->logger->info('Guard authentication successful!', ['token' => $token, 'authenticator' => \get_class($guardAuthenticator)]);

The AbstractToken class implements:
return sprintf('%s(user="%s", authenticated=%s, roles="%s")', $class, $this->getUsername(), json_encode($this->authenticated), implode(', ', $roles));

getUsername() often contains PII. I know it is the developers responsibility to configure monolog accordingly to avoid logging of PII, esp. in production environments.

But still, I would like to ask if you consider to change the default log level which is "debug" when installing the bundle initially to "error" or "notice" in the config/prod/monolog.yaml?

Thanks
Rico

**Comment by stof** [comment]
well, the default config is to use FingersCrossedHandler at error level with the stream handler inside it at debug level. This way, in case of an error, you get all the logs of the request to allow debugging. Logging only the error message would make debugging errors much harder.

**Comment by RicoFactset** [comment]
> well, the default config is to use FingersCrossedHandler at error level with the stream handler inside it at debug level. This way, in case of an error, you get all the logs of the request to allow debugging. Logging only the error message would make debugging errors much harder.

Makes sense. but does it not also make sense to configure prod's monolog.yaml at least differently (secure by design) when installing "composer require symfony/monolog-bundle"?

**Comment by lyrixx** [comment]
Monolog has a specific configuration for the prod environment.

You can find it here: https://github.com/symfony/recipes/blob/master/symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml
