### ISSUE TITLE
Annotation error in return of LoggerInterface.php

### ISSUE THREAD

**Issue by ConnectxWeb** [symfony/monolog-bundle#344]
Annotation error in LoggerInterface.php, return void instead of boolean

**Comment by xabbuh** [comment]
Can you be bit more precise please? What did you do and what was the exact error that you got?

**Comment by ConnectxWeb** [comment]
in LogInterface just replace "@return void" by "@return bool" for any functions, its an annotation error.

**Comment by xabbuh** [comment]
I don't understand which interface and methods you are talking about.

**Comment by ConnectxWeb** [comment]
I think its not the right reposity it should be this one that includes the default monolog bundle of Symfony:
https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php

**Comment by xabbuh** [comment]
But those methods are not supposed to return anything.

**Comment by ConnectxWeb** [comment]
they return a boolean

**Comment by xabbuh** [comment]
Which implementing are you taking about. The [implementation provided by Monolog](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php) does not return boolean values in these methods.

**Comment by ConnectxWeb** [comment]
in vendor:monolog:monolog:src:monolog:Logger.php
the return has been overloaded:
    /**
     * Adds a log record at the DEBUG level.
     *
     * This method allows for compatibility with common interfaces.
     *
     * @param  string $message The log message
     * @param  array  $context The log context
     * @return bool   Whether the record has been processed
     */
    public function debug($message, array $context = array())
    {
        return $this->addRecord(static::DEBUG, $message, $context);
    }

**Comment by xabbuh** [comment]
It seems indeed that Monolog returned values in 1.x. This has been changed in the 2.x release line.

**Comment by ConnectxWeb** [comment]
The latest version 4 of symfony has this problem but it has been updated for v5!
The declaration of the interface returns void so its allright now.
