### ISSUE TITLE
How to run the tests ?

### ISSUE THREAD

**Issue by rrajkomar** [symfony/monolog-bundle#347]
I'm trying to provide an implementation of a handler for Grafana Loki, but when I try to run the tests, I have a lot of other tests that are failing because of some missing services or handlers.
some examples : 
```
1) Symfony\Bundle\MonologBundle\Tests\DependencyInjection\MonologExtensionTest::testRollbarHandlerReusesNotifier
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "monolog.handler.main" has a dependency on a non-existent service "my_rollbar_id".
```

```
InvalidArgumentException: There is no handler class defined for handler "raven".
```

And some others (mailer, request_stack, etc.)

How do I fix these so I can test properly ?

**Comment by Tobion** [comment]
I guess #351 should solve this

**Comment by lyrixx** [comment]
Hello, Tests are OK now

This is cool for Loki 👍🏼 Don't hesitate to share your result with me (on [twitter](https://twitter.com/lyrixx) for example 🙏🏼 )
