### ISSUE TITLE
3.6.0 causes issues with Symfony 3.4 and custom log handler services

### ISSUE THREAD

**Issue by brusch** [symfony/monolog-bundle#365]
Since 3.6.0 we're encountering the following issue, but only when using with Symfony v3.4.45, with v4.4.15 all is working fine: 

```text
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Unused binding "Symfony\Contracts\HttpClient\HttpClientInterface" in service "instanceof.Monolog\Handler\HandlerInterface.0.Pimcore\Log\Handler\ApplicationLoggerDb". in /home/travis/build/pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php on line 50
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Unused binding "Symfony\Contracts\HttpClient\HttpClientInterface" in service "instanceof.Monolog\Handler\HandlerInterface.0.Pimcore\Log\Handler\ApplicationLoggerDb". in /home/travis/build/pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php on line 50
```

This is the used service definition: 
https://github.com/pimcore/pimcore/blob/416ed369e071cfab175b33b9a4596c130dbe1a29/bundles/CoreBundle/Resources/config/logging.yml#L33

This all seems to be related with this lines: 
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L158 

But I've currently no idea why this breaks the service definition in Symfony 3.4

**Comment by nicolas-grekas** [comment]
Bundles should never use bindings, they don't need to (neither any auto-*, nor named arguments ideally). This config should be made plain old config.

@brusch would you like sending a PR to update this?

**Comment by nicolas-grekas** [comment]
I should read more before commenting... This is a rule for autoconfiguration. It's fine.
3.4 doesn't support bindings in autoconfiguration, that's why I suppose.

**Comment by nicolas-grekas** [comment]
The bundle should drop support for 3.4 IMHO. IT's EOLedin a few weeks anyway.

**Comment by brusch** [comment]
Thanks a lot for the really fast response 👍
I'd be fine with dropping the support 😊
Alternatively we'd have to check for the auto-config support for bindings there, right?

**Comment by lyrixx** [comment]
I guess we can close this  issue?

**Comment by jdreesen** [comment]
As far as I understand this bundle should drop the support of Symfony 3.4 first.

**Comment by ninsuo** [comment]
While migrating a 10 years+ project from Symfony 3 to 4 and bumping monolog, I've got the issue.

If it can help others, I patched it by adding a useless HttpClient in the handler's constructor.

```php
public function __construct(HttpClientInterface $httpClient)
```

To be removed soon enough once in Symfony4+ :-)
