### ISSUE TITLE
Handle deprecation of the `actionLevel` argument in finger crossed strategies

### ISSUE THREAD

**Issue by Taluu** [symfony/monolog-bundle#369]
Form Symfony 6, the `actionLevel` must be an inner strategy instead of plain old value / string / int.

To prevent the deprecation, when creating the definition of the bridge's strategy, we should probably wrap the action level in an inner strategy as is done in the bridges ?

See https://github.com/symfony/monolog-bridge/blob/5.x/Handler/FingersCrossed/HttpCodeActivationStrategy.php#L39-L44 and https://github.com/symfony/monolog-bridge/blob/5.x/Handler/FingersCrossed/NotFoundActivationStrategy.php#L39-L44

**Comment by adrienfr** [comment]
Thank you @Taluu, it wasn't clear for me if the deprecation message was to be fixed with a `symfony/monolog-bundle` future update or a simple `config/packages/monolog.yaml` update.

**Comment by Taluu** [comment]
There shouldn't be anything to do on your part, the bundle should handle the strategy and use the right object instead IMO.

So this is an indirect deprecation.

**Comment by adrienfr** [comment]
@pvgnd already created a PR to fix this, see https://github.com/symfony/monolog-bundle/pull/336.

**Comment by pvgnd** [comment]
Actually the PR has to be updated, changes have been done on monolog after the PR opening

**Comment by pvgnd** [comment]
I updated the PR

**Comment by jokaorgua** [comment]
maybe anyone knows when a new release will be added with this fix?

**Comment by Taluu** [comment]
ping @lyrixx as he's usually the one in charge of merging / releasing things on this budle

**Comment by yassinehamouten** [comment]
We are all waiting for it

**Comment by luispabon** [comment]
Bump!

**Comment by nikserg** [comment]
Waiting for this!

**Comment by yassinehamouten** [comment]
For all who using symfony & PHPUnit and their pipelines are failing.

Insert in your phpunit.xml.dist

` <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" /> `
       in  `<php> ... ... </php>`

Reenable this rule when this error will be fixed.

**Comment by allan-simon** [comment]
but it will silence all deprecations, even those which are "actionable" by the developer ?

**Comment by yassinehamouten** [comment]
Yes, it will silent all deprecations errors.

Can PHPUnit silent only a specific error like PHPStan ?

**Comment by gimler** [comment]
https://symfony.com/doc/current/components/phpunit_bridge.html#configuration you have also the possibility to use a regex for that

**Comment by pscheit-lillydoo** [comment]
This does only increase the stacktrace, but does not ignore.

count the deprecations the monolog thingy is causing and do :

```
SYMFONY_DEPRECATIONS_HELPER=max[indirect]=10&max[direct]=0
```

which says: no deprecations from you but 10 from indirect sources

**Comment by guillaumesmo** [comment]
try the following 

`composer require "symfony/monolog-bundle:dev-master#bbf53e9c0077b011f5d3c1c391ef45a59c0133a2"`

**Comment by clee1999** [comment]
Currently I my `ActionLevel` is already an inner instead of of plain old value / string / int.
But it didn't fix the problem and I have the same error message : 
`Since symfony/monolog-bridge 5.2: Passing an actionLevel (int|string) as constructor's 3rd argument of "Symfony\Bridge\Monolog\Handler\FingersCrossed\HttpCodeActivationStrategy" is deprecated, "Monolog\Handler\FingersCrossed\ActivationStrategyInterface" expected.
`
