### ISSUE TITLE
Is it possible to pick a handler in run-time according to env variable

### ISSUE THREAD

**Issue by nivpenso** [symfony/monolog-bundle#371]
Hello,
My code is being used as a worker to costume Symfony Messenger messages as well as a webserver.

So basically I have 2 processes one for the webserver and one for the worker.

For the webserver, I'm using a FingersCrossed handler that that provides me all the log when the buffer closes or on a specific error, but unfortunately, this handler doesn't work for workers due to their lifecycle behavior - their process never dies, and therefore, the buffer "never ends" unless an error arrives

I'm trying to find a solution that will allow me to pick the logger's handler on run-time based on a parameter. Do you guys know about such logic?

**Comment by lyrixx** [comment]
Hello, I face the same issue, but I have solved it like that:

* I put a max log message on the FingerWrossed (50 IIRC)
* After each message, I reset the container, so Monolog is flushed if needed, then cleared

---

About having différent handler according to an env variable, this is not possible ATM.
You can submit a PR if you want. I'll be glad to merge it.

---

Thanks for your issue
