### ISSUE TITLE
How to use symfony_mailer alternative transport?

### ISSUE THREAD

**Issue by paseto** [symfony/monolog-bundle#372]
Could not find any docs related to this config.

According to [Symfony docs](https://symfony.com/doc/current/mailer.html#multiple-email-transports), I've already had working multiple transport config.
`

> mailer.yaml

     framework:
        mailer:
            transports:
                main: '%env(MAILER_DSN)%'
                alternative: '%env(MAILER_DSN_IMPORTANT)%'
`

Then I've configured like [here](https://symfony.com/doc/current/logging/monolog_email.html) and it's working for primary mailer dsn.
`

> monolog.yaml

    monolog:
      handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        deduplicated:
            type: deduplication
            #            path: "%kernel.logs_dir%/%kernel.environment%.log"
            #            level: debug
            handler: symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: 'error@gmail.com'
            to_email:   'support@gmail.com'
            subject:    'An Error Occurred! [%%datetime%%]'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html

How can I use my alternative mailer transport for symfony_mailer handler?

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
