### ISSUE TITLE
Deprecation: "Passing an actionLevel (int|string) as constructor's 3rd argument"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/monolog-bundle#378]
I'm upgrading some Symfony apps to Symfony 5.2-RC2 and I'm seeing this deprecation in all of them:

```
Other deprecation notices:

    Since symfony/monolog-bridge 5.2: Passing an actionLevel (int|string) as constructor's
    3rd argument of "Symfony\Bridge\Monolog\Handler\FingersCrossed\HttpCodeActivationStrategy"
    is deprecated, "Monolog\Handler\FingersCrossed\ActivationStrategyInterface" expected.
```

A `composer show` lists this:

```
symfony/monolog-bridge               v5.2.0-RC2 Symfony Monolog Bridge
symfony/monolog-bundle               v3.6.0     Symfony MonologBundle
```

I guess this should be fixed here ... but I might be wrong. Thanks!

**Comment by adrienfr** [comment]
Fixed with pending PR https://github.com/symfony/monolog-bundle/pull/336 from @pvgnd.
Already reported with https://github.com/symfony/monolog-bundle/issues/369

**Comment by javiereguiluz** [comment]
Closing as a duplicate of #369. thanks @adrienfr
