### ISSUE TITLE
Missing some Handlers in the Extension.php file ? (FallbackGroupHandler for example)

### ISSUE THREAD

**Issue by Neirda24** [symfony/monolog-bundle#379]
Hi.
I think some handlers are missing for the phpdoc in `MonologExtension.php`. At least the `FallbackGroupHandler`. But it was added in 2.0 and this bundle support both 1.x and 2.x. Maybe that's why ?

Thanks

**Comment by TimurFlush** [comment]
+1
What about the Telegram handler?
