### ISSUE TITLE
swift_mailer for error emails - is there a way to exclude 404?

### ISSUE THREAD

**Issue by jahr-quintet** [symfony/monolog-bundle#392]
Hi, I we have monolog and swift_mailer, however, we receive an error email for every 404 status, e.g., somebody calls /wp-admin. Is there any way to prevent this? Thanks!

Details on our config are here: https://stackoverflow.com/questions/66477593/symfony-5-monolog-avoid-error-emails-for-404/66483849#66483849

**Comment by jderusse** [comment]
Have a look to `excluded_404s` options.

**Comment by jahrralf** [comment]
Alright - but as you can see we have `excluded_http_codes``active with codes 404 and 405. Shouldn't this also filter filter away 404 codes? Or is this different? I cannot find any documentation about this, sorry.
