### ISSUE TITLE
Email Exception from Command?

### ISSUE THREAD

**Issue by men2326** [symfony/monolog-bundle#397]
Hi,
how to configure monolog to send an email-exception if there is an exception in the command (console),
I work with symfony 4, and the config of monolog.yaml is :
`main_swift:
            type: fingers_crossed
            action_level: error
            handler: swift
swift:
            type:       swift_mailer
            from_email: 'noryply@noreply.com'
            to_email:   ['noryply@noreply.com']
            subject:    '[ERRoR]'
            level:      notice
           ...`
It's work perfectly from app, but not if is command
I think the problem become from fingers_crossed, he expects to have an http error but when runnig from command it's not

Thanks!

**Comment by jderusse** [comment]
Hello and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.
