### ISSUE TITLE
Collision between ElasticSearchHandler and ElasticaHandler

### ISSUE THREAD

**Issue by javijavo** [symfony/monolog-bundle#424]
Hi,

I'm trying to set up monolog-bundle with native Elasticsearch cliente (introduced in monolog 2.0).
But it seems that I'm doing something wrong and I can't make it work.

Reviewing the code itself I've seen the following lines in MonologExtension:

https://github.com/symfony/monolog-bundle/blob/fde12fc628162787a4e53877abadc30047fd868b/DependencyInjection/MonologExtension.php#L983-L1011

There you can see that "elasticsearch" is always replaced with the ElasticaHandler in the array merge on line 1006.
Apart from that, I think the elastic handler should be ElasticsearchHandler, not ElasticSearchHandler (note te captial "S").

I locally did those changes but couldn't make it work and I'm lost.
Does symfony/monolog-bundle support the native Elasticsearch client? Or am I doing something wrong?

Many many thanks for your help

**Comment by mihaileu** [comment]
I have a similar issue, somehow on random application starts I receive error that Elastica is not found because is not installed. However it worked till now, something got changed somewhere.

**Comment by Seldaek** [comment]
Yeah the problem is ElasticSearchHandler was renamed to ElasticaHandler in monolog 2.0, and Elasticsearch was added at the same time. But here it was using elasticsearch and kept using elasticsearch for elastica.. now we're kinda in a mess. 

https://github.com/symfony/monolog-bundle/pull/438 should help resolve this/move things forward, then eventually we can drop the elasticsearch type.

**Comment by Chameleon-m** [comment]
elastic_search.host does not work, must be array
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L292
need array for elastic_search, and key "hosts", example:
`
$clientArguments = [
    'hosts' => [$handler['elasticsearch']['host']],
];
`
OR
`
$clientArguments = [
    'hosts' => $handler['elasticsearch']['hosts'],
];
`
And fix Configuration:
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L98
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L879
