### ISSUE TITLE
Production not works

### ISSUE THREAD

**Issue by grzegorz-stolarz** [symfony/monolog-bundle#427]
`bin/console c:c --env=prod -vvv`
`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                     
  Unrecognized option "monolog" under "monolog". Available options are "channels", "handlers", "use_microseconds"`

`composer show -i`
`symfony/monolog-bridge                   v5.4.3             Provides integration for Monolog with various Symfony components`
`symfony/monolog-bundle                   v3.7.1             Symfony MonologBundle`

`config/packages/prod/monolog.yaml`
`monolog:`
`    handlers:`
`        main:`
`            type: fingers_crossed`
`            action_level: info`
`            handler: nested`
`            excluded_http_codes: [404, 405, {200: ['^/ping(.+)']}]`
`            buffer_size: 50 # How many messages should be saved? Prevent memory leaks`
`            path:  "php://stderr"`
`            channels: ["!event", "!doctrine", "!php", "!security"]`
`        nested:`
`            type:  stream`
`            path:  "php://stderr"`
`            level: debug`
`        console:`
`            type: console`
`            process_psr_3_messages: false`
`            channels: ["!event", "!doctrine"]`
`        deprecation:`
`            type: stream`
`            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"`
`       deprecation_filter:`
`            type: filter`
`            handler: deprecation`
`            max_level: info`
`            channels: ["php"]`

**Comment by derrabus** [comment]
Please use https://github.com/symfony/symfony/discussions for support requests.
