### ISSUE TITLE
I cant upgrade for Monolog 3

### ISSUE THREAD

**Issue by selikov** [symfony/monolog-bundle#440]
Hi, see
https://github.com/symfony/monolog-bundle/blob/a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d/composer.json#L20
in composer.json "symfony/monolog-bridge": "~4.4 || ^5.0 || ^6.0",

^6.0 - its not include Monolog-bridge v6.1.0 wich support Monolog3.0

May be set "symfony/monolog-bridge": "~4.4 || ^5.0 || ^6.1" ?

**Comment by stof** [comment]
`^6.0` means `>=6.0 <7`, so this definitely allows using version 6.1.

However, Symfony 6.1 requires PHP 8.1, which might explain why you don't get it if you run composer on PHP 8.0.
