### ISSUE TITLE
Runtime environment variable support for log level

### ISSUE THREAD

**Issue by uncaught** [symfony/monolog-bundle#444]
Follow up to #357

It is inconvenient to have environment variables only be applied at container build time. This kind of defeats the purpose of environment variables and makes pre-building the container impossible.

By simply removing `levelToMonologConst` and using the parameters as they are, everything works beautifully at runtime.

The _only_ thing that won't happen is the thrown `\InvalidArgumentException` if the level is invalid. But validation of environment variables is _never_ done at compile time in any other situation. And this validation was only introduced by #357, which, in my opinion, should not have been accepted.

To avoid a BC-break due to the validation, I'd like to see an option to disable `levelToMonologConst`. I've checked all monolog handlers that use the level coming from `levelToMonologConst` and _all_ of them use `Monolog\Logger::toMonologLevel` to cast the level. There is no need to cast the level in this extension at build time. You might then make that the default behavior in a new major version and drop it eventually.

Would you be open to this change? What arguments are there for still having `levelToMonologConst`?

Is that validation even a BC-break if it was simply removed? It's not like a missing config validation will make anything stop working.

**Comment by GromNaN** [comment]
I have the same issue and made a PR that converts the value at runtime https://github.com/symfony/monolog-bundle/pull/446. I think there is no need for a breaking change nor a new option.
