### ISSUE TITLE
Incompatibility with monolog 3.x

### ISSUE THREAD

**Issue by TiMESPLiNTER** [symfony/monolog-bundle#453]
I wanted to use this bundle with monolog 3.x. But this major version of monolog introduced a new object called `LogRecord` which is used in the `HandlerInterface` method declarations instead of `array`. 

All the handlers and formatters in this bundle are therefore not compatible with monolog/monolog 3.x.

Either we need to fix the signature (should be easy) or exclude `^3.0` in composer.json.

For other people who have the same issue: you can as a workaround, explicitly set the dependency version of `monolog/monolog` to `^2.9.1` in your composer.json

**Comment by derrabus** [comment]
> All the handlers and formatters in this bundle are therefore not compatible with monolog/monolog 3.x.

This bundle does not contain any handlers and formatters.
