### ISSUE TITLE
Add support for `#[Target]` attribute to autowire channels

### ISSUE THREAD

**Issue by AlexMinaev19** [symfony/monolog-bundle#474]
## Problem

Currently, we have one documented solution for autowiring channels ([link](https://symfony.com/doc/current/logging/channels_handlers.html#how-to-autowire-logger-channels)). It's name-based approach the same as for Symfony HTTP Client ([link](https://symfony.com/doc/current/http_client.html#scoping-client)).

For example, to inject `foo_bar` channel you have to do the following:
```php
public function __construct(
     LoggerInterface $fooBarLogger,
) {
}
```

But it's not the best approach. As already mentioned, Symfony HTTP Client has similar functionality, but they moved further and introduced support for `#[Target]` attribute to decouple variable name and autowiring ([link](https://symfony.com/blog/new-in-symfony-5-3-service-autowiring-with-attributes#selecting-autowire-alias-with-attributes)).

## Proposition
Adds support for `#[Target]` attribute for autowiring channels.

For example,
```php
public function __construct(
    #[Target('foo_bar')]
    LoggerInterface $logger,
) {
}
```

**Comment by lyrixx** [comment]
It's already possible, for example I use : 

```php
        #[Target('monolog.logger.billing')]
        private readonly LoggerInterface $logger = new NullLogger(),
```

**Comment by stof** [comment]
MonologBundle supports the `WithMonologChannel` attribute available in Monolog 3, which has the additional benefit that it also hooks into the _discovery_ of which channels to create.

**Comment by lyrixx** [comment]
I'm closing this issue, since I guess everything is okay

**Comment by AlexMinaev19** [comment]
Thank you, guys! I didn't know about it and the documentation has no info. But good to know!

**Comment by lyrixx** [comment]
@AlexMinaev19 If you could contribute to the documentation, it would be awesome!
